v = input('Digite algo: ')
print('Alnum:', v.isalnum())
print('Alpha:', v.isalpha())
print('Ascii:', v.isascii())
print('Digit:', v.isdigit())
print('Lower:', v.islower())
print('Decimal:', v.isdecimal())
print('Identifier:', v.isidentifier())
print('Numeric:', v.isnumeric())
print('Printable:', v.isprintable())
print('Space:', v.isspace())
print('Title:', v.istitle())
print('Digit:', v.isdigit())
print('Upper:', v.isupper())
